apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
        - name: ic-webapp
          image: safouane95/ic-webapp:1.0
          env:
            - name: ODOO_URL
              value: http://172.180.0.59:30959/
            - name: PGADMIN_URL
              value: http://172.180.0.59:32728/
          ports:
            - containerPort: 8080
