apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: odoo
          image: odoo:15
          securityContext:
            runAsUser: 0  # ✅ Exécution du conteneur en root
          env:
            - name: HOST
              value: postgres
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          ports:
            - containerPort: 8069
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo-storage
      volumes:
        - name: odoo-storage
          persistentVolumeClaim:
            claimName: odoo-pvc
