apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: icgroup
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres


apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: icgroup
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
  type: NodePort



apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: icgroup
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
